# Generated by Django 3.2.5 on 2021-11-23 13:03

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fitweb', '0002_auto_20211123_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='video',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, default=''),
        ),
    ]
