# Generated by Django 3.2.5 on 2021-11-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitweb', '0003_auto_20211123_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='Header_first',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='image',
            name='Header_second',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='image',
            name='Header_third',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='Header_first',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='Header_second',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='Header_third',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
