# Generated by Django 3.2.5 on 2021-11-25 10:45

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fitweb', '0004_auto_20211124_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Header_third',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
