# Generated by Django 3.2.5 on 2021-11-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitweb', '0005_auto_20211125_1945'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
