# Generated by Django 3.2.5 on 2021-11-27 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitweb', '0009_auto_20211127_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
