# Generated by Django 3.2.5 on 2021-11-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitweb', '0010_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Header_four',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
