# Generated by Django 3.2.5 on 2021-12-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitweb', '0011_post_header_four'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='objects_num',
            field=models.IntegerField(),
        ),
    ]
